version = 0.1

[default.deploy.parameters]
stack_name = "github-gpt-wrapper"
resolve_s3 = true
s3_prefix = "github-gpt-wrapper"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GithubOwner=\"REDACTED_OWNER\" DefaultBaseBranch=\"main\" BranchPrefix=\"gpt\""
image_repositories = []

[default.global.parameters]
region = "us-east-2"
